package app;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import beans.Bank;


public class App {

	public static void main(String[] args) throws Exception {
		
		ApplicationContext context = new ClassPathXmlApplicationContext("resources/spring.xml");
		Bank b = (Bank)context.getBean("bank");
		b.deposite();
		b.withdraw();
		b.interestRate();
		System.out.println(b.getClass().getCanonicalName()); //class generated by CGLIB at runtime, it is 
		//a proxy class. in which interest rate definition has been overridden.
	}

}
